# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 11, 33, 10, 682818)),
        ),
    ]
