# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 17:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20160120_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 1, 21, 19, 6, 4, 869156))),
                ('start_point', models.CharField(max_length=254)),
                ('start_point_coordinates', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=254)),
                ('end_point_coordinates', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('noob_friendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
